# syntax=docker/dockerfile:1

FROM node:20-alpine AS builder
WORKDIR /app

# Vite embeds these values at build time; pass production HTTPS URLs in CI/deploy.
ARG VITE_API_URL
ARG VITE_APP_URL
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_SUPABASE_STORAGE_BUCKET_PUBLIC
ARG VITE_SUPABASE_STORAGE_BUCKET_PRIVATE

ARG VITE_PAYMENT_PROVIDER
ARG VITE_ENABLE_PAYMENT_SIMULATOR
ARG VITE_ENABLE_QA_PAYMENT_SIMULATION

ARG VITE_CLIENT_BOOKING_ENABLED
ARG VITE_CLIENT_CITAS_ENABLED
ARG VITE_CLIENT_PLAN_PURCHASE_ENABLED
ARG VITE_CLIENT_LOCK_MESSAGE

ARG VITE_VIP_MEMBERSHIPS_ENABLED
ARG VITE_VIP_MEMBERSHIPS_LOCK_MESSAGE
ARG VITE_VIP_MEMBERSHIPS_PURCHASE_ENABLED
ARG VITE_VIP_MEMBERSHIPS_PURCHASE_LOCK_MESSAGE

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_APP_URL=$VITE_APP_URL
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_SUPABASE_STORAGE_BUCKET_PUBLIC=$VITE_SUPABASE_STORAGE_BUCKET_PUBLIC
ENV VITE_SUPABASE_STORAGE_BUCKET_PRIVATE=$VITE_SUPABASE_STORAGE_BUCKET_PRIVATE

ENV VITE_PAYMENT_PROVIDER=$VITE_PAYMENT_PROVIDER
ENV VITE_ENABLE_PAYMENT_SIMULATOR=$VITE_ENABLE_PAYMENT_SIMULATOR
ENV VITE_ENABLE_QA_PAYMENT_SIMULATION=$VITE_ENABLE_QA_PAYMENT_SIMULATION

ENV VITE_CLIENT_BOOKING_ENABLED=$VITE_CLIENT_BOOKING_ENABLED
ENV VITE_CLIENT_CITAS_ENABLED=$VITE_CLIENT_CITAS_ENABLED
ENV VITE_CLIENT_PLAN_PURCHASE_ENABLED=$VITE_CLIENT_PLAN_PURCHASE_ENABLED
ENV VITE_CLIENT_LOCK_MESSAGE=$VITE_CLIENT_LOCK_MESSAGE

ENV VITE_VIP_MEMBERSHIPS_ENABLED=$VITE_VIP_MEMBERSHIPS_ENABLED
ENV VITE_VIP_MEMBERSHIPS_LOCK_MESSAGE=$VITE_VIP_MEMBERSHIPS_LOCK_MESSAGE
ENV VITE_VIP_MEMBERSHIPS_PURCHASE_ENABLED=$VITE_VIP_MEMBERSHIPS_PURCHASE_ENABLED
ENV VITE_VIP_MEMBERSHIPS_PURCHASE_LOCK_MESSAGE=$VITE_VIP_MEMBERSHIPS_PURCHASE_LOCK_MESSAGE

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine AS runner

RUN rm -f /etc/nginx/conf.d/default.conf \
  && printf '%s\n' \
    'server {' \
    '  listen 80;' \
    '  server_name _;' \
    '' \
    '  root /usr/share/nginx/html;' \
    '  index index.html;' \
    '' \
    '  location / {' \
    '    try_files $uri $uri/ /index.html;' \
    '  }' \
    '' \
    '  location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot)$ {' \
    '    expires 7d;' \
    '    add_header Cache-Control "public, immutable";' \
    '  }' \
    '}' \
    > /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
