$path = "src\features\admin\pages\AdminCitasPreviewPage.jsx"
$lines = [IO.File]::ReadAllLines($path, [Text.Encoding]::UTF8)

# Keep lines 0-1263 (everything up to and including `    }),`)
# Then append the correct dep array and return statement
$keepLines = $lines[0..1263]

$newTail = @(
'    [',
'      activeBlock,',
'      effectiveActiveBlockIndex,',
'      addCompanionBlock,',
'      allBlocksComplete,',
'      allowCompanions,',
'      availabilityError,',
'      availabilityLoading,',
'      availabilityMap,',
'      barbers,',
'      barbersLoading,',
'      bookingBlocks,',
'      bookingBlocksSummary,',
'      branchList,',
'      canAddCompanionBlock,',
'      canGoPrevMonth,',
'      contextData,',
'      currentMonth,',
'      fetchAvailability,',
'      goToAgenda,',
'      goToBarberos,',
'      goToConfirm,',
'      holdDurationMin,',
'      holdResult,',
'      holdSubmitting,',
'      isPastSlotForToday,',
'      minBookingDateKey,',
'      monthRange,',
'      onSelectDay,',
'      onSelectTime,',
'      paymentRequired,',
'      selectedBarber,',
'      selectedBarberId,',
'      selectedBranch,',
'      selectedBranchId,',
'      selectedDate,',
'      selectedServices,',
'      selectedTime,',
'      serviceIds,',
'      services,',
'      servicesAtEnd,',
'      servicesCanScroll,',
'      servicesLoading,',
'      setActiveBlock,',
'      setMonth,',
'      selectSuggestedBarber,',
'      slotConflict,',
'      slotSuggestions,',
'      slotSuggestionsLoading,',
'      slots,',
'      slotsLoading,',
'      submitHold,',
'      syncServicesScrollState,',
'      toggleService,',
'      totalToPay,',
'      updateActiveBlockBarber,',
'      updateBlockAtIndex,',
'      selectBarber,',
'      selectBranch,',
'    ]',
'  );',
'',
'  return (',
'    <div className="mf-page citas-page public-booking-page public-booking-preview-scope">',
'      <div className="citas-toolbar">',
'        <span className="citas-mode-pill">Modo Vista Previa - Simulacion (sin hold real)</span>',
'        <div className="citas-stepper">',
'          {PREVIEW_STEPS.map((step) => (',
'            <button',
'              key={step.id}',
'              type="button"',
'              className={`citas-step-btn ${previewStep === step.id ? ''`''is-active''`'' : ''''}`}',
'              disabled={!previewCanOpenStep[step.id]}',
'              onClick={() => selectPreviewStep(step.id)}',
'            >',
'              {step.label}',
'            </button>',
'          ))}',
'        </div>',
'      </div>',
'',
'      {contextLoading ? (',
'        <div className="citas-surface p-6">',
'          <LoadingSpinner />',
'        </div>',
'      ) : null}',
'      {contextError ? <ErrorBanner message={contextError} onRetry={fetchContext} /> : null}',
'',
'      {!contextLoading && !contextError ? (',
'        <div className="public-booking-main">',
'          <PublicBookingProvider value={contextValue}>',
'            {previewStep === ''`''barberos''`'' ? <PublicBookingBarberosStep /> : null}',
'            {previewStep === ''`''agenda''`'' ? <PublicBookingAgendaStep /> : null}',
'            {previewStep === ''`''confirmar''`'' ? <PublicBookingConfirmStep /> : null}',
'          </PublicBookingProvider>',
'        </div>',
'      ) : null}',
'    </div>',
'  );',
'}',
''
)

# Replace backtick-escaped single quotes back to normal JSX
$result = $keepLines + $newTail

[IO.File]::WriteAllLines($path, $result, [Text.Encoding]::UTF8)
Write-Output ("Done. Total lines: " + $result.Length)
